"""
Signal Generator

Generates trading signals based on planetary configurations,
aspects, retrogrades, and lunar cycles.
"""

from datetime import datetime, timedelta
from typing import Optional, List, Dict, Any
import uuid

from app.services.astrology.calculator import AstrologyCalculator
from app.services.astrology.aspects import AspectCalculator
from app.services.astrology.moon import MoonCalculator
from app.services.signals.rules import SignalRules
from app.core.constants import ASPECTS, DEFAULT_ASSETS, PLANETS


def format_planet_name(planet_key: str) -> str:
    """Convert planet key to display name (e.g., 'rahu' -> 'North Node')"""
    if planet_key in PLANETS:
        return PLANETS[planet_key]["name"]
    return planet_key.replace("_", " ").title()


class SignalGenerator:
    """
    Generates trading signals based on astrological configurations.

    Signals are generated by analyzing:
    - Planetary aspects (conjunctions, squares, trines, etc.)
    - Retrograde periods
    - Sign ingresses
    - Lunar cycles
    """

    def __init__(self, system: str = "western"):
        self.system = system
        self.calculator = AstrologyCalculator(system=system)
        self.aspect_calc = AspectCalculator()
        self.moon_calc = MoonCalculator()
        self.rules = SignalRules()

    def _generate_signal_id(self) -> str:
        """Generate a unique signal ID"""
        return str(uuid.uuid4())[:8]

    def _get_signal_direction(
        self,
        aspects: List[Dict[str, Any]],
        retrogrades: List[Dict[str, Any]]
    ) -> str:
        """
        Determine signal direction based on astrological factors.

        Returns: bullish, bearish, neutral, or volatile
        """
        harmonious = sum(1 for a in aspects if a["nature"] == "harmonious")
        challenging = sum(1 for a in aspects if a["nature"] == "challenging")

        # Retrograde Mercury often indicates confusion/volatility
        mercury_retro = any(r["planet"] == "mercury" for r in retrogrades)

        if mercury_retro and challenging > harmonious:
            return "volatile"
        elif harmonious > challenging + 2:
            return "bullish"
        elif challenging > harmonious + 2:
            return "bearish"
        else:
            return "neutral"

    def _get_signal_strength(self, aspects: List[Dict[str, Any]]) -> str:
        """Determine signal strength from aspects"""
        if not aspects:
            return "weak"

        avg_strength = sum(a["strength"] for a in aspects) / len(aspects)

        if avg_strength >= 8:
            return "very_strong"
        elif avg_strength >= 6:
            return "strong"
        elif avg_strength >= 4:
            return "moderate"
        else:
            return "weak"

    def _get_relevant_markets(
        self,
        aspects: List[Dict[str, Any]]
    ) -> List[str]:
        """
        Determine which markets are most affected by the aspects.

        Based on traditional planetary rulerships:
        - Jupiter: expansion, growth - affects all markets positively
        - Saturn: restriction, discipline - caution signals
        - Uranus: sudden changes - crypto, tech stocks
        - Neptune: illusion, oil/gas, pharmaceuticals
        - Pluto: transformation, power - major market shifts
        """
        markets = set()
        planets_involved = set()

        for aspect in aspects:
            planets_involved.add(aspect["planet1"])
            planets_involved.add(aspect["planet2"])

        # All markets if major planets involved
        if "jupiter" in planets_involved or "saturn" in planets_involved:
            markets.update(["crypto", "stocks", "commodities"])

        # Uranus = crypto/tech volatility
        if "uranus" in planets_involved:
            markets.add("crypto")
            markets.add("stocks")

        # Neptune = oil, gas, commodities
        if "neptune" in planets_involved:
            markets.add("commodities")

        # Mars = energy, action
        if "mars" in planets_involved:
            markets.add("commodities")
            markets.add("crypto")

        # Venus = finance, luxury goods
        if "venus" in planets_involved:
            markets.add("stocks")

        # Default to all if no specific associations
        if not markets:
            markets = {"crypto", "stocks", "commodities"}

        return list(markets)

    def get_active_signals(
        self,
        market: Optional[str] = None,
        min_strength: str = "moderate"
    ) -> List[Dict[str, Any]]:
        """
        Get currently active trading signals.

        Args:
            market: Optional market filter
            min_strength: Minimum signal strength

        Returns:
            List of active signals
        """
        signals = []
        now = datetime.utcnow()

        # Get current astrological state
        positions = self.calculator.get_all_positions(now)
        aspects = self.aspect_calc.find_all_aspects(positions, min_strength=5)
        retrogrades = self.calculator.get_retrograde_planets(now)
        moon_phase = self.moon_calc.get_current_phase(now)

        # Generate aspect-based signals
        for aspect in aspects[:5]:  # Top 5 strongest aspects
            direction = self._get_signal_direction([aspect], retrogrades)
            strength = self._get_signal_strength([aspect])
            markets = self._get_relevant_markets([aspect])

            if market and market not in markets:
                continue

            signal = {
                "id": self._generate_signal_id(),
                "timestamp": now,
                "signal_type": "aspect",
                "direction": direction,
                "strength": strength,
                "markets": markets,
                "assets": self._get_suggested_assets(markets),
                "trigger": f"{format_planet_name(aspect['planet1'])}-{format_planet_name(aspect['planet2'])} {aspect['aspect_type']}",
                "planetary_config": {
                    "aspect": aspect,
                    "retrogrades": [r["planet"] for r in retrogrades],
                },
                "description": self._generate_aspect_description(aspect, direction),
                "expires": now + timedelta(days=aspect["orb"] + 1),
            }
            signals.append(signal)

        # Generate retrograde-based signals
        for retro in retrogrades:
            if retro["planet"] in ["mercury", "venus", "mars"]:
                signal = {
                    "id": self._generate_signal_id(),
                    "timestamp": now,
                    "signal_type": "retrograde",
                    "direction": "volatile" if retro["planet"] == "mercury" else "bearish",
                    "strength": "moderate",
                    "markets": ["crypto", "stocks", "commodities"],
                    "assets": None,
                    "trigger": f"{format_planet_name(retro['planet'])} Retrograde",
                    "planetary_config": {"retrograde": retro},
                    "description": self._generate_retrograde_description(retro),
                    "expires": retro.get("ends"),
                }
                signals.append(signal)

        # Generate lunar signals
        if moon_phase["phase_name"] in ["New Moon", "Full Moon"]:
            lunar_signal = {
                "id": self._generate_signal_id(),
                "timestamp": now,
                "signal_type": "lunar",
                "direction": "volatile",
                "strength": "strong" if moon_phase["phase_name"] == "Full Moon" else "moderate",
                "markets": ["crypto", "stocks", "commodities"],
                "assets": None,
                "trigger": moon_phase["phase_name"],
                "planetary_config": {"moon_phase": moon_phase},
                "description": self._generate_lunar_description(moon_phase),
                "expires": now + timedelta(days=3),
            }
            signals.append(lunar_signal)

        # Filter by minimum strength
        strength_order = ["weak", "moderate", "strong", "very_strong"]
        min_idx = strength_order.index(min_strength)
        signals = [s for s in signals if strength_order.index(s["strength"]) >= min_idx]

        return signals

    def _get_suggested_assets(self, markets: List[str]) -> List[str]:
        """Get suggested assets for given markets"""
        assets = []
        for market in markets:
            if market in DEFAULT_ASSETS:
                assets.extend(DEFAULT_ASSETS[market][:2])
        return assets[:5]

    def _generate_aspect_description(
        self,
        aspect: Dict[str, Any],
        direction: str
    ) -> str:
        """Generate human-readable description for an aspect signal"""
        nature = aspect["nature"]
        p1 = format_planet_name(aspect["planet1"])
        p2 = format_planet_name(aspect["planet2"])
        aspect_name = aspect["aspect_type"].title()

        if nature == "harmonious":
            return f"{p1}-{p2} {aspect_name} suggests favorable conditions. {direction.title()} bias for affected markets."
        elif nature == "challenging":
            return f"{p1}-{p2} {aspect_name} indicates tension and potential volatility. Exercise caution."
        else:
            return f"{p1}-{p2} {aspect_name} is active. Watch for {direction} movement in markets."

    def _generate_retrograde_description(self, retro: Dict[str, Any]) -> str:
        """Generate description for retrograde signal"""
        planet = format_planet_name(retro["planet"])

        descriptions = {
            "Mercury": "Mercury Retrograde active - expect communication errors, tech glitches, and market confusion. Avoid major decisions.",
            "Venus": "Venus Retrograde - financial matters may face delays or reversals. Review investments carefully.",
            "Mars": "Mars Retrograde - energy and momentum may stall. Not ideal for aggressive trading.",
        }

        return descriptions.get(planet, f"{planet} is retrograde. Consider its traditional rulerships for market impact.")

    def _generate_lunar_description(self, phase: Dict[str, Any]) -> str:
        """Generate description for lunar signal"""
        if phase["phase_name"] == "New Moon":
            return f"New Moon in {phase['moon_sign']} - fresh beginnings, time to set intentions. Markets may see reversals."
        else:
            return f"Full Moon in {phase['moon_sign']} - heightened emotions and culmination energy. Expect increased volatility."

    def get_signal_history(
        self,
        days: int = 30,
        market: Optional[str] = None
    ) -> List[Dict[str, Any]]:
        """
        Get historical signals.

        Note: In production, this would query a database.
        For now, returns simulated historical data.
        """
        # Placeholder - would query database in production
        return []

    def get_upcoming_signals(
        self,
        days: int = 7,
        market: Optional[str] = None
    ) -> List[Dict[str, Any]]:
        """Get predicted signals for upcoming astrological events"""
        upcoming = []
        now = datetime.utcnow()

        # Check each day for significant configurations
        for day in range(1, days + 1):
            future_date = now + timedelta(days=day)
            positions = self.calculator.get_all_positions(future_date)
            aspects = self.aspect_calc.find_all_aspects(positions, min_strength=7)

            for aspect in aspects[:2]:
                markets = self._get_relevant_markets([aspect])
                if market and market not in markets:
                    continue

                upcoming.append({
                    "date": future_date,
                    "event_type": "aspect",
                    "trigger": f"{format_planet_name(aspect['planet1'])}-{format_planet_name(aspect['planet2'])} {aspect['aspect_type']}",
                    "strength": self._get_signal_strength([aspect]),
                    "markets": markets,
                    "description": f"Upcoming {aspect['aspect_type']} between {format_planet_name(aspect['planet1'])} and {format_planet_name(aspect['planet2'])}",
                })

        return upcoming

    def get_signals_by_aspect(self, aspect_type: str) -> List[Dict[str, Any]]:
        """Get signals filtered by aspect type"""
        all_signals = self.get_active_signals()
        return [
            s for s in all_signals
            if s["signal_type"] == "aspect"
            and s["planetary_config"].get("aspect", {}).get("aspect_type") == aspect_type
        ]

    def get_signals_by_planet(self, planet: str) -> List[Dict[str, Any]]:
        """Get signals involving a specific planet"""
        all_signals = self.get_active_signals()
        filtered = []

        for signal in all_signals:
            if signal["signal_type"] == "aspect":
                aspect = signal["planetary_config"].get("aspect", {})
                if planet in [aspect.get("planet1"), aspect.get("planet2")]:
                    filtered.append(signal)
            elif signal["signal_type"] == "retrograde":
                retro = signal["planetary_config"].get("retrograde", {})
                if retro.get("planet") == planet:
                    filtered.append(signal)

        return filtered

    def get_retrograde_alerts(self) -> List[Dict[str, Any]]:
        """Get alerts for retrograde planets"""
        retrogrades = self.calculator.get_retrograde_planets()
        alerts = []

        for retro in retrogrades:
            alerts.append({
                "planet": retro["planet"],
                "sign": retro["sign"],
                "alert_level": "high" if retro["planet"] == "mercury" else "moderate",
                "message": self._generate_retrograde_description(retro),
                "trading_advice": self._get_retrograde_trading_advice(retro["planet"]),
            })

        return alerts

    def _get_retrograde_trading_advice(self, planet: str) -> str:
        """Get trading advice for retrograde planet"""
        advice = {
            "mercury": "Avoid signing contracts. Double-check all orders. Expect delays.",
            "venus": "Review portfolio. Not ideal for new investments. Focus on value.",
            "mars": "Reduce position sizes. Avoid aggressive trades. Patience recommended.",
            "jupiter": "Reassess growth strategies. Internal expansion over external.",
            "saturn": "Review risk management. Strengthen discipline.",
        }
        return advice.get(planet, "Consider the planet's traditional rulerships for guidance.")

    def get_lunar_signals(self) -> List[Dict[str, Any]]:
        """Get signals based on lunar cycles"""
        moon_phase = self.moon_calc.get_current_phase()
        signals = []

        # Current phase signal
        signals.append({
            "phase": moon_phase["phase_name"],
            "sign": moon_phase["moon_sign"],
            "illumination": moon_phase["illumination"],
            "signal": self._get_lunar_trading_signal(moon_phase),
        })

        # Upcoming lunar events
        calendar = self.moon_calc.get_lunar_calendar(datetime.utcnow(), 14)
        for event in calendar[:3]:
            signals.append({
                "date": event["date"],
                "event": event["event_type"],
                "sign": event["sign"],
                "signal": self._get_lunar_event_signal(event),
            })

        return signals

    def _get_lunar_trading_signal(self, phase: Dict[str, Any]) -> Dict[str, Any]:
        """Get trading signal for current moon phase"""
        phase_signals = {
            "New Moon": {"direction": "neutral", "advice": "Time for new beginnings. Set trading intentions."},
            "Waxing Crescent": {"direction": "bullish", "advice": "Building phase. Consider entries."},
            "First Quarter": {"direction": "volatile", "advice": "Action point. Make decisions."},
            "Waxing Gibbous": {"direction": "bullish", "advice": "Refine positions. Growth continues."},
            "Full Moon": {"direction": "volatile", "advice": "Peak energy. Watch for reversals."},
            "Waning Gibbous": {"direction": "bearish", "advice": "Distribution phase. Consider exits."},
            "Last Quarter": {"direction": "volatile", "advice": "Release point. Let go of losing trades."},
            "Waning Crescent": {"direction": "bearish", "advice": "Rest phase. Avoid major trades."},
        }
        return phase_signals.get(phase["phase_name"], {"direction": "neutral", "advice": "Observe market conditions."})

    def _get_lunar_event_signal(self, event: Dict[str, Any]) -> Dict[str, Any]:
        """Get signal for upcoming lunar event"""
        event_type = event["event_type"]

        if event_type == "new_moon":
            return {"importance": "high", "effect": "Potential market bottom or beginning of new trend"}
        elif event_type == "full_moon":
            return {"importance": "high", "effect": "Potential market top or trend exhaustion"}
        else:
            return {"importance": "moderate", "effect": "Transition point - watch for momentum shifts"}
